### ISSUE TITLE
Hyperkin Duke Xbox One/Windows 10 Controller, works but not out the box

### ISSUE THREAD

**Issue by Arranmc182** [paroj/xpad#106]
If anyone want to use the Hyperkin Duke Controller on Linux here is a quick how to ;)

Install xpad driver
Then open terminal type "sudo rmmod xpad"
Then type "sudo modprobe xpad"
Then "sudo nano /sys/bus/usb/drivers/xpad/new_id"
and add "2e24 0652" then save & close.

If done correctly the controller should now function correctly, controller does reboot every 40 seconds when not active just keep steam open to fix issue, the "sudo rmmod xpad" command maybe optional depends if you already have the driver running.

This just seems like xpad Driver is just not aware of the new USB Device ID for the controller and I'm sure it will be integrated at some point, there has been a patch already submitted to the kernel to add the USB ID directly to the kernel [>>HERE<<](https://patchwork.kernel.org/patch/10421897/) 

Video of Controller running in jstest [>>HERE<<](https://www.youtube.com/watch?v=wFwLpkPMqvg)

**Comment by Arranmc182** [comment]
To get this automated I just made a file called "new_id" and added the USB ID to it then made a script to just copy this over every time I log in. 

This is my script.

#!/bin/bash

echo YOUROWNPASSWORD | sudo -S rmmod xpad
echo YOUROWNPASSWORD | sudo -S modprobe xpad
echo YOUROWNPASSWORD | sudo -S cp /home/arran/Documents/xpad/new_id /sys/bus/usb/drivers/xpad/new_id

Now the controller will work without having to manually load the device ID every time.

**Comment by Arranmc182** [comment]
This is the system I tested this on

OS: Ubuntu 18.04 bionic
Kernel: x86_64 Linux 4.18.3-041803-generic
Shell: bash 4.4.19
Resolution: 1920x1080
DE: MATE 1.20.0
WM: Compiz
CPU: AMD FX-8350 Eight-Core @ 8x 4GHz [18.7°C]
 GPU: GeForce GTX 970

**Comment by Deerskin** [comment]
What's the output of `lsusb -v` when the controller is plugged in?

**Comment by Arranmc182** [comment]
I would check out this video its not mine but should give more info [https://www.youtube.com/watch?v=zYTMTaeB0P4](url)

**Comment by parkerlreed** [comment]
````
Bus 001 Device 004: ID 2e24:0652  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass       255 Vendor Specific Subclass
  bDeviceProtocol       255 Vendor Specific Protocol
  bMaxPacketSize0        64
  idVendor           0x2e24 
  idProduct          0x0652 
  bcdDevice            1.01
  iManufacturer           1 DDR
  iProduct                2 Hyperkin Duke
  iSerial                 3 0000976F10C8B159
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0060
    bNumInterfaces          3
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     71 
      bInterfaceProtocol    208 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               4
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               4
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     71 
      bInterfaceProtocol    208 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     71 
      bInterfaceProtocol    208 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x08  EP 8 OUT
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x00e4  1x 228 bytes
        bInterval               1
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x87  EP 7 IN
        bmAttributes            1
          Transfer Type            Isochronous
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x00e4  1x 228 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       0
      bNumEndpoints           0
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     71 
      bInterfaceProtocol    208 
      iInterface              0 
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        2
      bAlternateSetting       1
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass     71 
      bInterfaceProtocol    208 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
can't get device qualifier: Resource temporarily unavailable
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0002
  (Bus Powered)
  Remote Wakeup Enabled
````

**Comment by parkerlreed** [comment]
Any info on when this might get into mainline?

**Comment by parkerlreed** [comment]
Also Steam only detects it as generic controller when using this method. Is there a way to get it to see it as an Xbox controller?

**Comment by parkerlreed** [comment]
Found the upstream mentioning the reboot issue https://patchwork.kernel.org/patch/10421897/

**Comment by Arranmc182** [comment]
> Also Steam only detects it as generic controller when using this method. Is there a way to get it to see it as an Xbox controller?

This is common issue with 3rd party Xbox One controllers, I no longer own then the duske as sold it on to buy other controllers so far have found the 2 other one a PDP & other PowerA both got detected as generic xinput controllers so steams will only see it as generic controller, but some games will detect it as an xbox controller just fine with out help from steam but other will not.

**Comment by MARKMENTAL** [comment]
Just used the OP's instructions to get my hyperkin duke working with openSUSE Leap 15.2. Thanks a bunch!!

**Comment by ThisNekoGuy** [comment]
Is there a reason why this hasn't been added to the driver yet?
I'd have thought support for this would have been added 3-4 years ago... :woozy_face:

**Comment by paroj** [comment]
actually, it has been added:
https://github.com/paroj/xpad/blob/0585a19cee92756bb916c8f08c808bbd6c70eeff/xpad.c#L313

so, we probably can close this.

**Comment by ThisNekoGuy** [comment]
> actually, it has been added

@paroj You say this but I still have this problem with kernel 5.14.21 with the driver in it :/
It always reboots constantly and only behaves when Steam is on, per the suggesting in the first post here

**Comment by Malsententia** [comment]
5.18.16 here, it's still an issue.
