### ISSUE TITLE
Pull upstream xpad PDP quirk change

### ISSUE THREAD

**Issue by cgutman** [paroj/xpad#122]
Please rebase to get my PDP patch upstream - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/drivers/input/joystick/xpad.c?id=a6754fae1e66e9a40fed406290d7ca3f2b4d227c

This should address these PDP PRs and issues:
https://github.com/paroj/xpad/pull/104
https://github.com/paroj/xpad/pull/105
https://github.com/paroj/xpad/pull/108
https://github.com/paroj/xpad/pull/109
https://github.com/paroj/xpad/pull/112
https://github.com/paroj/xpad/pull/115
https://github.com/paroj/xpad/pull/116
https://github.com/paroj/xpad/issues/117

**Comment by paroj** [comment]
done

**Comment by paroj** [comment]
but still need to upstream this, no?
https://github.com/paroj/xpad/commit/a66c53c008572db516a60a8d38ef4f823b3d3980

**Comment by ewtoombs** [comment]
@cgutman: I tried the driver without my patch and it didn't work. That was a while ago, though, and I don't really have a way of figuring out what version it was I tested that failed. What version should I be trying?

**Comment by ewtoombs** [comment]
@cgutman I just confirmed, it definitely will not work without the PR I just put through. So yeah, accept it please.
