### ISSUE TITLE
Move to mainline kernel ?

### ISSUE THREAD

**Issue by tomleb** [paroj/xpad#135]
Hi,

just bought a controller and I was surprised that it did not work out of the box with the kernel's xpad module. It works fine with your module though.

I was wondering, are there any reason to not push this upstream to add it to the mainline kernel ?

I would be interested in helping doing that. From ./scripts/get_maintainer.pl, it seems like the person to contact is Dmitry Torokhov <dmitry.torokhov@gmail.com>.

**Comment by paroj** [comment]
see https://github.com/paroj/xpad/issues/159#issuecomment-756734217

actually this is synced about once a year with mainline. Its just a PITA to push patches through the mailing list workflow used by the kernel.

**Comment by vinicius-daros** [comment]
> see [#159 (comment)](https://github.com/paroj/xpad/issues/159#issuecomment-756734217)
> 
> actually this is synced about once a year with mainline. Its just a PITA to push patches through the mailing list workflow used by the kernel.

Would be possible for someone to upstream it for you?
