### ISSUE TITLE
Shanwan Generic 2.4 Dongle Type xbox

### ISSUE THREAD

**Issue by zeunus** [paroj/xpad#152]
Hi, i'm amateur user of Batocera Linux, but I know this system integrated your driver.
I have a control, but no conects with the system.
I accompany dmesg
![shanwan](https://user-images.githubusercontent.com/67354990/85679411-62ac5700-b697-11ea-883e-7ecdddf6cf34.png)

**Comment by paroj** [comment]
not going to read a screenshot
