### ISSUE TITLE
What is the latest stable version?

### ISSUE THREAD

**Issue by ralf1307** [paroj/xpad#159]
@paroj 
I want to package this dkms driver for postmarketOS, what should I follow?

The git tags were 5 years ago, the dkms version didnt change since 2015 but there is activity in the master branch.
Git tags with this format (v1.0.3) are the easiest to follow.

**Comment by paroj** [comment]
the latest stable version is shipped with linux upstream. This is more of a staging area for hotfixes while also allowing to use them with older linux versions.

See this for a (rough) diff to upstream:
https://github.com/paroj/xpad/compare/upstream...master

**Comment by ralf1307** [comment]
Thank you!
