### ISSUE TITLE
No one is allowed to use xpad

### ISSUE THREAD

**Issue by noob-nine** [paroj/xpad#180]
Adding a license would be nice, otherwise people are just allowed to view your source code.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.
[[https://choosealicense.com/no-permission/)](https://choosealicense.com/no-permission/)]

**Comment by paroj** [comment]
https://github.com/paroj/xpad/blob/0585a19cee92756bb916c8f08c808bbd6c70eeff/xpad.c#L1
