### ISSUE TITLE
do not drop force feedback packets

### ISSUE THREAD

**Issue by paroj** [paroj/xpad#2]
while the `URB ffff88020d047d80 submitted while active` issue is fixed in master, FFB packets might still be dropped.
Consider [this patch for SteamOS](https://github.com/ValveSoftware/steamos_kernel/pull/21).

However I first need a way to reproduce this. Using fftest is not enough to triggering the error.

**Comment by Basaltq** [comment]
Related? http://steamcommunity.com/app/233130/discussions/0/611702631210587760/#c611702631214382829

**Comment by paroj** [comment]
yes, related. but the linked patch is a better solution.

**Comment by paroj** [comment]
according to dtor one should not use a queue. makes sense.
http://www.spinics.net/lists/linux-input/msg40708.html

**Comment by paroj** [comment]
and this is a test for reproducing the race:
```
while true; do
        for i in $(seq 0 5); do
                echo $i > /sys/class/leds/xpad0/subsystem/xpad0/brightness
        done
done
```

**Comment by paroj** [comment]
re-submitting logic is now in master: 906c1f1aeef2c2969f1e5c42ea954e9572cb26c4.
verified that LED commands get correctly re-submitted.
Still need a test for FF commands. Otherwise done.

**Comment by paroj** [comment]
actually this particular problem is fixed. the next one is in #10
