### ISSUE TITLE
Proposal: Add quirks field to IDs table

### ISSUE THREAD

**Issue by endrift** [paroj/xpad#211]
Added in commit f26624873768e14dcb4dd0e8f913bcf8cff1fa0a is an initialization sequence that's [skipped for all but one specific controller](https://github.com/paroj/xpad/commit/f26624873768e14dcb4dd0e8f913bcf8cff1fa0a#diff-3d985fe7837dec4db1df27733cece3b37633535ef91b1cbdf1c8b6eec4f692dbR1270-R1283). I have another controller here (HORIPAD FPS for Nintendo Switch, 0f0d:00dc) that also requires that sequence. While I could manually check for that VID/PID too, I think a better approach would be to add a quirks field to the ID table at the top with a bit for the 360 init path. While that might not be sufficient for all matches, it's certainly sufficient for some, as this Hori device doesn't lie about its VID/PID like some clones do.

**Comment by paroj** [comment]
feel free to create a PR with your proposal
