### ISSUE TITLE
Bogus error check of usb_control_msg() during is_shanwan initialization

### ISSUE THREAD

**Issue by 1c7718e7** [paroj/xpad#216]
Commit https://github.com/paroj/xpad/commit/13ad3fa437e13c410d98cc2ec9c71c9a1f92b155, which adds initialization code for SHANWAN controllers, also (unintentionally?) changes the error check of `status = usb_control_msg(...)` from `if (status < 0)` to `if (status)`  (line 1400). Predictably, this makes opening the device fail with EINVAL.

Changing the line back to `if (status < 0)` makes my shanwan controller (Yula GXT 540) work just fine, thanks to the recently added init code.

**Comment by paroj** [comment]
fixed
