### ISSUE TITLE
Xbox One Elite Controller Crash

### ISSUE THREAD

**Issue by pathammer** [paroj/xpad#24]
Just wanted to document that this module does not support the Xbox One Elite controller. Here's the syslog when it's connected:

> Feb 12 10:38:09 ph kernel: [ 1563.206414] usb 3-8.4.1: USB disconnect, device number 16
Feb 12 10:38:35 ph kernel: [ 1589.245090] usb 3-8.4.1: new full-speed USB device number 17 using xhci_hcd
Feb 12 10:38:36 ph kernel: [ 1589.334372] usb 3-8.4.1: New USB device found, idVendor=045e, idProduct=02dd
Feb 12 10:38:36 ph kernel: [ 1589.334375] usb 3-8.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 12 10:38:36 ph kernel: [ 1589.334377] usb 3-8.4.1: Product: Controller
Feb 12 10:38:36 ph kernel: [ 1589.334378] usb 3-8.4.1: Manufacturer: Microsoft
Feb 12 10:38:36 ph kernel: [ 1589.334379] usb 3-8.4.1: SerialNumber: 7EED89C19B94
Feb 12 10:38:36 ph mtp-probe: checking bus 3, device 17: "/sys/devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4.1"
Feb 12 10:38:36 ph mtp-probe: bus: 3, device: 17 was not an MTP device
Feb 12 10:38:36 ph kernel: [ 1589.340462] input: Microsoft X-Box One pad (Firmware 2015) as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4.1/3-8.4.1:1.0/input/input23
Feb 12 10:38:36 ph kernel: [ 1589.340512] xpad 3-8.4.1:1.0: xpad_prepare_next_out_packet - found pending output packet 0
Feb 12 10:38:36 ph kernel: [ 1589.340573] usbcore: registered new interface driver xpad
Feb 12 10:38:36 ph kernel: [ 1589.354574] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -2
Feb 12 10:38:36 ph kernel: [ 1589.384650] xpad 3-8.4.1:1.0: xpad_prepare_next_out_packet - found pending output packet 0
Feb 12 10:38:36 ph kernel: [ 1589.394624] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -2
Feb 12 10:38:59 ph /py3status: message repeated 58 times: [ user method getText failed (getText() takes 1 positional argument but 3 were given)]
Feb 12 10:39:00 ph /py3status: i3status set_time_modules time failed ('e' is a bad directive in format '%A %e.%B - %l:%M   %Y %m %d')
Feb 12 10:39:00 ph /py3status: message repeated 6 times: [ i3status set_time_modules time failed ('e' is a bad directive in format '%A %e.%B - %l:%M   %Y %m %d')]
Feb 12 10:39:00 ph /py3status: user method getText failed (getText() takes 1 positional argument but 3 were given)
Feb 12 10:39:00 ph /py3status: i3status set_time_modules time failed ('e' is a bad directive in format '%A %e.%B - %l:%M   %Y %m %d')
Feb 12 10:39:00 ph /py3status: i3status set_time_modules time failed ('e' is a bad directive in format '%A %e.%B - %l:%M   %Y %m %d')
Feb 12 10:39:01 ph /py3status: user method getText failed (getText() takes 1 positional argument but 3 were given)
Feb 12 10:39:05 ph kernel: [ 1618.511994] xpad 3-8.4.1:1.0: xpad_prepare_next_out_packet - found pending output packet 0
Feb 12 10:39:05 ph kernel: [ 1618.528107] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -2
Feb 12 10:39:08 ph kernel: [ 1621.322810] xpad 3-8.4.1:1.0: xpad_prepare_next_out_packet - found pending output packet 0
Feb 12 10:39:48 ph kernel: [ 1661.783950] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.788028] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.792026] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.795981] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.799944] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.804024] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.808023] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.811976] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.815938] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.819952] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.823951] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.827950] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.831949] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.835941] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.839939] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.844007] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.848005] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.852006] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.856006] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.860003] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.864003] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.867997] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.871999] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.875938] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.879924] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.883935] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.887932] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.891930] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.895925] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.899923] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.903922] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.907917] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.911915] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.915915] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.919911] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.923909] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.927908] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.931903] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.935902] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.939900] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.943897] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.947896] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.951895] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.955891] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.959961] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.963959] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.967880] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.971879] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.975943] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.979943] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.983870] xpad 3-8.4.1:1.0: xpad_irq_in - nonzero urb status received: -71
Feb 12 10:39:48 ph kernel: [ 1661.986678] usb 3-8.4.1: USB disconnect, device number 17
Feb 12 10:39:48 ph kernel: [ 1661.988798] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -108
Feb 12 10:39:56 ph kernel: [ 1670.115733] usb 3-8.4.1: new full-speed USB device number 18 using xhci_hcd
Feb 12 10:39:56 ph kernel: [ 1670.204837] usb 3-8.4.1: New USB device found, idVendor=045e, idProduct=02e3
Feb 12 10:39:56 ph kernel: [ 1670.204840] usb 3-8.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Feb 12 10:39:56 ph kernel: [ 1670.204841] usb 3-8.4.1: Product: Controller
Feb 12 10:39:56 ph kernel: [ 1670.204843] usb 3-8.4.1: Manufacturer: Microsoft
Feb 12 10:39:56 ph kernel: [ 1670.204844] usb 3-8.4.1: SerialNumber: 7EED8E5DB06C
Feb 12 10:39:56 ph kernel: [ 1670.205637] xpad 3-8.4.1:1.0: xpad_prepare_next_out_packet - found pending output packet 2
Feb 12 10:39:56 ph kernel: [ 1670.205690] input: Generic X-Box pad as /devices/pci0000:00/0000:00:14.0/usb3/3-8/3-8.4/3-8.4.1/3-8.4.1:1.0/input/input24
Feb 12 10:39:56 ph kernel: [ 1670.205934] BUG: unable to handle kernel NULL pointer dereference at 000000000000004e
Feb 12 10:39:56 ph kernel: [ 1670.205937] IP: [<ffffffffc120dc63>] xpad_probe+0x293/0x5d0 [xpad]
Feb 12 10:39:56 ph kernel: [ 1670.205950] PGD 0 
Feb 12 10:39:56 ph kernel: [ 1670.205951] Oops: 0000 [#1] SMP 
Feb 12 10:39:56 ph kernel: [ 1670.205953] Modules linked in: xpad(OE) ff_memless des_generic md4 nls_utf8 cifs fscache ipt_MASQUERADE iptable_nat nf_nat_ipv4 nf_nat nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack ipt_REJECT xt_CHECKSUM iptable_mangle xt_tcpudp bridge stp llc ip6table_filter ip6_tables iptable_filter ip_tables ebtable_nat ebtables x_tables bnep rfcomm bluetooth 6lowpan_iphc binfmt_misc snd_hda_codec_hdmi hp_wmi sparse_keymap intel_rapl x86_pkg_temp_thermal intel_powerclamp coretemp nvidia(POE) kvm_intel kvm crct10dif_pclmul crc32_pclmul ghash_clmulni_intel snd_usb_audio aesni_intel snd_usbmidi_lib aes_x86_64 lrw gf128mul glue_helper ablk_helper snd_hda_codec_realtek snd_hda_codec_generic cryptd snd_seq_midi snd_seq_midi_event snd_hda_intel snd_hda_controller snd_hda_codec dm_multipath joydev scsi_dh snd_hwdep nouveau snd_rawmidi snd_seq snd_pcm cp210x serio_raw mxm_wmi snd_seq_device wmi usbserial video snd_timer ttm drm_kms_helper snd drm lpc_ich mei_me i2c_algo_bit mei soundcore shpchp ppdev parport_pc tpm_infineon lp nls_iso8859_1 parport mac_hid uas usb_storage hid_generic hid_logitech_dj usbhid hid e1000e ahci ptp psmouse libahci pps_core
Feb 12 10:39:56 ph kernel: [ 1670.206004] CPU: 6 PID: 74 Comm: khubd Tainted: P           OE 3.16.0-33-generic #44~14.04.1-Ubuntu
Feb 12 10:39:56 ph kernel: [ 1670.206005] Hardware name: Hewlett-Packard HP Z230 Tower Workstation/1905, BIOS L51 v01.42 11/17/2014
Feb 12 10:39:56 ph kernel: [ 1670.206006] task: ffff880416e78000 ti: ffff880416e80000 task.ti: ffff880416e80000
Feb 12 10:39:56 ph kernel: [ 1670.206008] RIP: 0010:[<ffffffffc120dc63>]  [<ffffffffc120dc63>] xpad_probe+0x293/0x5d0 [xpad]
Feb 12 10:39:56 ph kernel: [ 1670.206010] RSP: 0018:ffff880416e838f8  EFLAGS: 00010206
Feb 12 10:39:56 ph kernel: [ 1670.206011] RAX: ffff8803e0b30480 RBX: ffff88040c2bd800 RCX: ffff8800c12b4000
Feb 12 10:39:56 ph kernel: [ 1670.206013] RDX: 0000000000000048 RSI: 0000000000000008 RDI: ffff8803e0b30540
Feb 12 10:39:56 ph kernel: [ 1670.206014] RBP: ffff880416e83930 R08: ffff8803ff995080 R09: ffffffff81568a5a
Feb 12 10:39:56 ph kernel: [ 1670.206015] R10: ffff88041d003800 R11: ffffea00105bd000 R12: ffff8800c12b4000
Feb 12 10:39:56 ph kernel: [ 1670.206016] R13: ffff8800c12b4090 R14: 0000000000000060 R15: ffff8803df135400
Feb 12 10:39:56 ph kernel: [ 1670.206017] FS:  0000000000000000(0000) GS:ffff88042dd80000(0000) knlGS:0000000000000000
Feb 12 10:39:56 ph kernel: [ 1670.206018] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
Feb 12 10:39:56 ph kernel: [ 1670.206019] CR2: 000000000000004e CR3: 0000000002c13000 CR4: 00000000001407e0
Feb 12 10:39:56 ph kernel: [ 1670.206021] Stack:
Feb 12 10:39:56 ph kernel: [ 1670.206022]  04ffffff814c30a2 ffff8803df135510 ffff8800c12b4090 ffff8800c12b4000
Feb 12 10:39:56 ph kernel: [ 1670.206024]  ffffffffc1211068 ffff88040c2bd830 ffffffffc12111a0 ffff880416e83978
Feb 12 10:39:56 ph kernel: [ 1670.206025]  ffffffff8156e21f 0000000016e83950 ffff88040c2bd800 ffff88040c2bd830
Feb 12 10:39:56 ph kernel: [ 1670.206027] Call Trace:
Feb 12 10:39:56 ph kernel: [ 1670.206033]  [<ffffffff8156e21f>] usb_probe_interface+0x1df/0x330
Feb 12 10:39:56 ph kernel: [ 1670.206037]  [<ffffffff814b914d>] driver_probe_device+0x12d/0x3e0
Feb 12 10:39:56 ph kernel: [ 1670.206039]  [<ffffffff814b9400>] ? driver_probe_device+0x3e0/0x3e0
Feb 12 10:39:56 ph kernel: [ 1670.206041]  [<ffffffff814b943b>] __device_attach+0x3b/0x40
Feb 12 10:39:56 ph kernel: [ 1670.206043]  [<ffffffff814b71b3>] bus_for_each_drv+0x63/0xa0
Feb 12 10:39:56 ph kernel: [ 1670.206046]  [<ffffffff814b8fa8>] device_attach+0x88/0xa0
Feb 12 10:39:56 ph kernel: [ 1670.206048]  [<ffffffff814b8438>] bus_probe_device+0x98/0xc0
Feb 12 10:39:56 ph kernel: [ 1670.206050]  [<ffffffff814b62a4>] device_add+0x4f4/0x630
Feb 12 10:39:56 ph kernel: [ 1670.206052]  [<ffffffff8156c08b>] usb_set_configuration+0x4fb/0x810
Feb 12 10:39:56 ph kernel: [ 1670.206054]  [<ffffffff815769fe>] generic_probe+0x2e/0xa0
Feb 12 10:39:56 ph kernel: [ 1670.206056]  [<ffffffff8156dff2>] usb_probe_device+0x32/0x80
Feb 12 10:39:56 ph kernel: [ 1670.206058]  [<ffffffff814b914d>] driver_probe_device+0x12d/0x3e0
Feb 12 10:39:56 ph kernel: [ 1670.206060]  [<ffffffff814b9400>] ? driver_probe_device+0x3e0/0x3e0
Feb 12 10:39:56 ph kernel: [ 1670.206062]  [<ffffffff814b943b>] __device_attach+0x3b/0x40
Feb 12 10:39:56 ph kernel: [ 1670.206064]  [<ffffffff814b71b3>] bus_for_each_drv+0x63/0xa0
Feb 12 10:39:56 ph kernel: [ 1670.206066]  [<ffffffff814b8fa8>] device_attach+0x88/0xa0
Feb 12 10:39:56 ph kernel: [ 1670.206068]  [<ffffffff814b8438>] bus_probe_device+0x98/0xc0
Feb 12 10:39:56 ph kernel: [ 1670.206070]  [<ffffffff814b62a4>] device_add+0x4f4/0x630
Feb 12 10:39:56 ph kernel: [ 1670.206072]  [<ffffffff81561288>] usb_new_device+0x3c8/0x790
Feb 12 10:39:56 ph kernel: [ 1670.206074]  [<ffffffff8156a432>] ? usb_get_descriptor+0x82/0xc0
Feb 12 10:39:56 ph kernel: [ 1670.206076]  [<ffffffff815624d8>] hub_port_connect+0x578/0xa00
Feb 12 10:39:56 ph kernel: [ 1670.206078]  [<ffffffff81563153>] hub_events+0x7f3/0xce0
Feb 12 10:39:56 ph kernel: [ 1670.206081]  [<ffffffff81563675>] hub_thread+0x35/0x160
Feb 12 10:39:56 ph kernel: [ 1670.206084]  [<ffffffff810b4d10>] ? prepare_to_wait_event+0x100/0x100
Feb 12 10:39:56 ph kernel: [ 1670.206086]  [<ffffffff81563640>] ? hub_events+0xce0/0xce0
Feb 12 10:39:56 ph kernel: [ 1670.206089]  [<ffffffff81091312>] kthread+0xd2/0xf0
Feb 12 10:39:56 ph kernel: [ 1670.206092]  [<ffffffff81091240>] ? kthread_create_on_node+0x1c0/0x1c0
Feb 12 10:39:56 ph kernel: [ 1670.206095]  [<ffffffff8176bdbc>] ret_from_fork+0x7c/0xb0
Feb 12 10:39:56 ph kernel: [ 1670.206097]  [<ffffffff81091240>] ? kthread_create_on_node+0x1c0/0x1c0
Feb 12 10:39:56 ph kernel: [ 1670.206098] Code: bf 54 01 00 00 03 48 8b 4b 08 4d 8b 87 88 00 00 00 48 8b 49 18 0f 95 c2 48 8d 34 d5 00 00 00 00 48 01 f2 48 8d 14 d1 49 8b 4f 10 <0f> b6 7a 06 0f b6 52 02 8b 31 48 89 48 48 4c 89 40 68 c7 80 88 
Feb 12 10:39:56 ph kernel: [ 1670.206118] RIP  [<ffffffffc120dc63>] xpad_probe+0x293/0x5d0 [xpad]
Feb 12 10:39:56 ph kernel: [ 1670.206120]  RSP <ffff880416e838f8>
Feb 12 10:39:56 ph kernel: [ 1670.206121] CR2: 000000000000004e
Feb 12 10:39:56 ph kernel: [ 1670.206123] ---[ end trace 7ad4cee274d90638 ]---
Feb 12 10:39:56 ph kernel: [ 1670.217283] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -2
Feb 12 10:39:56 ph kernel: [ 1670.233277] xpad 3-8.4.1:1.0: xpad_irq_in - urb shutting down with status: -2

Let me know if I can provide more info to help debug.

**Comment by LiranV** [comment]
Take a look at this #23

**Comment by pathammer** [comment]
@LiranV beautiful, this is a duplicate then.
