### ISSUE TITLE
Xbox One issues

### ISSUE THREAD

**Issue by enricostano** [paroj/xpad#26]
Hi! We're having troubles with the latest Xbox One controller. You can find more details here https://bbs.archlinux.org/viewtopic.php?id=208569

Can someone shade some light? Thanks! :smiley:

**Comment by john5788** [comment]
Duplicate of https://github.com/paroj/xpad/issues/19

**Comment by enricostano** [comment]
This worked for me https://github.com/ValveSoftware/steamos_kernel/blob/bcb20f5bbbe333ef12d5efda6207e7b84578e85d/drivers/input/joystick/xpad.c
