### ISSUE TITLE
New NACON Pro Compact Device ID

### ISSUE THREAD

**Issue by ronlaws86** [paroj/xpad#284]
This device isn't picked up by xpad as it has a slight variation in the device ID, I'm guessing a different board revision out in the wild. 
lsusb: 
`ID 3285:0603 NACON Pro Compact`
dmesg
```
[23692.118378] usb 3-8: new full-speed USB device number 28 using xhci_hcd
[23692.245655] usb 3-8: New USB device found, idVendor=3285, idProduct=0603, bcdDevice= 1.01
[23692.245660] usb 3-8: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[23692.245662] usb 3-8: Product: Pro Compact
[23692.245663] usb 3-8: Manufacturer: NACON
[23692.245664] usb 3-8: SerialNumber: 000001016A1505A2
```

**Comment by DJawna** [comment]
@ronlaws86  the problem is the maintainer of this repo seems to have left the project! i had the same issue like you (i also have a nacon controller that is not in the list of ids) and i solved it by forking the project and adding my nacon controller id myself. you can see it here:
https://github.com/DJawna/xpad

**Comment by ronlaws86** [comment]
> @ronlaws86 the problem is the maintainer of this repo seems to have left the project! i had the same issue like you (i also have a nacon controller that is not in the list of ids) and i solved it by forking the project and adding my nacon controller id myself. you can see it here: https://github.com/DJawna/xpad
> 
> the pr branch i did: [DJawna@21b5c6d](https://github.com/DJawna/xpad/commit/21b5c6d213ffeca77e89175b26af62b0c9f84041)

That's basically what I Did in my PR referenced above too. I've got it working, I wonder who's maintaining XPAD now? since it's included int he kernel I think? :thinking:

**Comment by paroj** [comment]
> I wonder who's maintaining XPAD now?

I still intend to update this repo and merge your changes. I am just short on time right now and will need to first merge back any changes that were done in the kernel version first.

To answer your maintenance question: the xpad driver in the kernel is maintained by the kernel developers and you can send your changes there directly following this guide:
https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html

However, it is not as easy as contributing on github and your changes will only appear in the next kernel release. Hence the purpose of this repo.

**Comment by ronlaws86** [comment]
> > I wonder who's maintaining XPAD now?
> 
> I still intend to update this repo and merge your changes. I am just short on time right now and will need to first merge back any changes that were done in the kernel version first.
> 
> To answer your maintenance question: the xpad driver in the kernel is maintained by the kernel developers and you can send your changes there directly following this guide: https://www.kernel.org/doc/html/v4.17/process/submitting-patches.html
> 
> However, it is not as easy as contributing on github and your changes will only appear in the next kernel release. Hence the purpose of this repo.

Good to know! I marked my PR as a duplicate and closed it anyway, as it is the same as another PR submitting the same line as someone else 2 or so months ago, it can be safely discarded as it doesn't offer anything more than that one.
