### ISSUE TITLE
PATCH: correctly sort vendor id's

### ISSUE THREAD

**Issue by dantob** [paroj/xpad#32]
Not able to directly create a pull request from gitlab, but please pull commit 690ccc53cb93789fda0f8c7c54996aca6bf7adc4 from https://gitlab.com/dan.g.tob/xpad.git 

https://gitlab.com/dan.g.tob/xpad/commit/690ccc53cb93789fda0f8c7c54996aca6bf7adc4

**Comment by paroj** [comment]
this URL would directly allow to download the patch: https://gitlab.com/dan.g.tob/xpad/commit/690ccc53cb93789fda0f8c7c54996aca6bf7adc4.patch

furthermore:
https://gitlab.com/rojtberg/xpad
