### ISSUE TITLE
Xbox One Covert Forces Not Responsive

### ISSUE THREAD

**Issue by DarkProjects** [paroj/xpad#49]
I can see the controller in jstest but it does not respond to any button or axis changes.

korey@DarkTower /usr/src/xpad-0.4 $ jstest /dev/input/js0 
Driver version is 2.1.0.
Joystick (Microsoft X-Box One pad (Covert Forces)) has 8 axes (X, Y, Z, Rx, Ry, Rz, Hat0X, Hat0Y)
and 11 buttons (BtnX, BtnY, BtnTL, BtnTR, BtnTR2, BtnSelect, BtnThumbL, BtnThumbR, ?, ?, ?).
Testing ... (interrupt to exit)
Axes:  0:     0  1:     0  2:-32767  3:     0  4:     0  5:-32767  6:     0  7:     0 Buttons:  0:off  1:off  2:off  3:off  4:off  5:off  6:off  7:off  8:off  9:off 10:off ^C

**Comment by cgutman** [comment]
It looks like you're not actually running this xpad module. If you did, it would appear as "Microsoft X-Box One pad (Firmware 2015)" instead of "Microsoft X-Box One pad (Covert Forces)".
