### ISSUE TITLE
Error when installing on Antergos

### ISSUE THREAD

**Issue by Hungry-Hobo** [paroj/xpad#55]
I tried to install the driver doing what the directions said, and got this error message when I typed "sudo dkms install -m xpad -v 0.4":
`Creating symlink /var/lib/dkms/xpad/0.4/source ->`
                           `/usr/src/xpad-0.4`
`DMKS: add completed`
`Error! echo`
`Your kernel headers for kernel 4.8.10-1-ARCH cannot be found at`
`/usr/lib/modules/4.8.10-1-ARCH/build or /usr/lib/modules/4.8.10-1-ARCH/source.`

**Comment by cgutman** [comment]
4.8 is pretty new. I don't think anything substantial is present in here that isn't upstream yet. What are you trying to fix by using this driver?

**Comment by Hungry-Hobo** [comment]
When I plug in an Xbox One controller it turns on but won't register any button presses in any of the games I tried. I thought using this driver would fix the problem.

**Comment by cgutman** [comment]
Can you post the output of `lsusb -v` for your controller? And also `dmesg` when plugging in the controller?

**Comment by paroj** [comment]
regarding your installation error: you are missing the kernel headers.

**Comment by paroj** [comment]
no response by submitter
