### ISSUE TITLE
xpad spamming kernel log

### ISSUE THREAD

**Issue by Erdk** [paroj/xpad#81]
Around line 760 in function ```xpad_prepare_next_out packet``` there is call:
```
dev_dbg(&xpad->intf->dev, ...
```

Which causes:
```
$ dmesg | grep xpad_prepare_next | wc -l 4214
```
In around ~10min.

Maybe show this message when specific option is turned on? Such as "debug" or something similar.

**Comment by paroj** [comment]
done
