### ISSUE TITLE
Bloating Raspberry Pi 3 Logs: 

### ISSUE THREAD

**Issue by Ignamious** [paroj/xpad#82]
Three files are effected in the var/log/ folder randomly

debug
kern.log
syslog

All have the same issue of of spamming:
 kernel: [1465653.203794] xpad 1-1.3:1.0: xpad_irq_in - nonzero urb status received: -32
 kernel: [1465653.203883] xpad 1-1.3:1.4: xpad_irq_in - nonzero urb status received: -32
 kernel: [1465653.203894] xpad 1-1.3:1.6: xpad_irq_in - nonzero urb status received: -32
 kernel: [1465653.204758] xpad 1-1.3:1.2: xpad_irq_in - nonzero urb status received: -32

This incident happened only 3 hours ago today, with the debug file being 37,097,245 lines w/ nano and a size of 4,340,377,478 Bytes (for debug purposes)

This is written thousands of times per second. leading to file sizes of 4gb each. This happens about once a month. i only notice it because i only have 9 GB of free space on the SD card left before the cascade. I am going to unplug the wireless XBOX360 adapter and see if this shows on any logs again (checking every few days or so).

**Comment by paroj** [comment]
done
